### PR TITLE
Additional Fluxbb tests and fixes

### PR DESCRIPTION
**Pull request by Firefishy**
* Add `[code]` to markdown support
* Use more standard `<s>` instead of github's `~~`
* Fix newline requirement for quote

### CODE REVIEW

**Comment by Firefishy** [comment]
@harry-wood Any chance you could merge this PR into your branch? Maybe squash it.

**Comment by harry-wood** [comment]
I was very puzzled about why the `~~` strikethrough syntax would give issues (bear in mind that I tested this stuff on https://community.openstreetmap.org and https://meta.discourse.org/ and importing into a discourse docker image, so I _know_ that `~~` works!) but I think I've got to the bottom of it

I see where someone was pointing out that it didn't work. https://community.openstreetmap.org/t/migrating-content-from-old-forums/446/152 . Their example coming [from this original bbcode](https://forum.openstreetmap.org/post.php?tid=19334&qid=333799https://forum.openstreetmap.org/post.php?tid=19334&qid=333799) involving [s] within a [list]. I believe strikethrough must have worked fine everywhere else, but not within a list, and ... bad news... we have a [list] problem that goes beyond strikethrough.

I took the decision to do [list][*] syntax conversion to into html `<ul><li>` rather than trying to do markdown list syntax. I thought it would be more trouble free, given how awkward markdown lists are with their indentation. Trying to get the indentation right especially for nested lists... that's nasty. But I've just realised...

When we give discourse an `<li>` tag with content in it, _all_ syntax support is disabled on that first line. Try pasting this into a discourse:
```
<ul>
<li>**bold?** *italic* ~~strikethrough~~  [url]http://google.com[/url]</li>
</ul>
```
But perhaps we can still avoid markdown list indentation hell. Try this.

```
<ul>
<li>

**bold?** *italic* ~~strikethrough~~  [url]http://google.com[/url]</li>
</ul>
```
Not pretty, but this works! So maybe we can just bung in some extra newlines after every `<li>`. The joys of discourse syntax parsing quirks.

So I guess I'll add that into the list handling logic, which is over in the discourse PR (regex preprocessing logic. Not in this gem)

Here we need to take out changes to do with strikethrough. Unless I'm mistaken, that was fine as I had it.

**Comment by Firefishy** [comment]
`~~` was not supported in discourse when I checked. See: https://meta.discourse.org/t/please-add-strikethrough-and-underline-support-in-markdown/22843

**Comment by Firefishy** [comment]
> I see where someone was pointing out that it didn't work. https://community.openstreetmap.org/t/migrating-content-from-old-forums/446/152 . Their example coming [from this original bbcode](https://forum.openstreetmap.org/post.php?tid=19334&qid=333799https://forum.openstreetmap.org/post.php?tid=19334&qid=333799) involving [s] within a [list]. I believe strikethrough must have worked fine everywhere else, but not within a list, and ... bad news... we have a [list] problem that goes beyond strikethrough.

This was fixed. The older posts was where I was still testing multiple different versions of the importer.
There are some list item discourse specific fixes here: https://github.com/Firefishy/discourse/commits/osm-test-import

Please focus just on this PR.

**Comment by Firefishy** [comment]
There have been no issues raised about the formatting on the test import site for the last few weeks despite me asking. In my view the fluxbb bbcode -> discourse markdown is now "good enough".

Please only look at comments AFTER the last import: https://community.openstreetmap.org/t/migrating-content-from-old-forums/446/164?u=firefishy

**Comment by harry-wood** [comment]
I didn't merge this directly, but I've just finished picking through it. We can close it. I've cherry-picked / taken inspiration from here into my PR: https://github.com/nlalonde/ruby-bbcode-to-md/pull/6 

I didn't bring in the `<s>` change because I've done fix to the `<li>` issue over in the discourse PR https://github.com/discourse/discourse/pull/18953/commits/5e86c4311ee94db8ffebff447ea96d6c105c55a8  ...which I believe is the only problem there.

**Pull request closed without merging**
